### ISSUE TITLE
widen range of drizzle-orm peer dependency

### ISSUE THREAD

**Issue by elijaholmos** [xantiagoma/drizzle-cursor#15]
With the release of drizzle-orm v0.30.x, this package is incompatible with any projects that use any drizzle version beyond v0.29.x.  Carat dependencies in package.json have a special behavior for 0.x versions; they only allow increments of the patch version and not the minor version (https://stackoverflow.com/a/77837308/8396479)

**Comment by xantiagoma** [comment]
Version published https://www.npmjs.com/package/drizzle-cursor/v/0.4.1
